Feature branch
Krishnabot/Apple-clone pull request #2
Opened 2020-01-28 08:49 UTC by Krishnabot

2020-01-28 10:38 UTC, nikasulo requested changes
# Great job! @Krishnabot 
You have put in a lot of effort and it's glaring. Please consider my comments below, make necessary adjustments and submit for another review :handshake: 

#### Descriptive PR
You need a more descriptive PR as it is a hard requirement. Consider describing the work you have completed in the branch in as much detail as you can and even include a link to the live project to speed up your review!
![screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png)

#### Horizontal Scroll
You seem to have a little bug with one of the elements of the page, shooting out beyond the browser's maximum width. This may be as a result of a margin or padding you have set up. One of the easiest ways I have found to correct this issue is to set the default `box-sizing` property to `border-box` as follows `*{box-sizing: border-box}`. Please read some more about it [here](https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing).
![screenshot](https://images2.imgbox.com/69/43/JqkSp20A_o.png)
![screenshot](https://images2.imgbox.com/5e/9a/2bvLikXR_o.png)

#### Live link
Please remember to update the live link in your project to point to the actual website. My go to resource for making live links is [Raw Githack](https://raw.githack.com) Please check it out, it's free and easy to use :+

### Summary
Your work is really amazing, please consider the changes I am proposing and it will all come together. See you at the top! :rocket: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-01-28 13:46 UTC, MauricioRobayo requested changes
Hi @Krishnabot!

It's looking great!

Still some small issues need to be fixed:


- [x] The dividers are overflowing the navbar, make sure to fix that 😊:

![image](https://user-images.githubusercontent.com/2121481/73268483-06f1a680-41a9-11ea-9742-05d5515825c6.png)

- [x] Footer is misaligned. The copyright `p` should be inside the `footer` tag:

![image](https://user-images.githubusercontent.com/2121481/73268970-eaa23980-41a9-11ea-942c-9b0a07e61000.png)

**[OPTIONAL]**: You are doing great with the semantic markup 🚀. You could do better if instead of a `div` for the main content you use the `main` tag.

Status: **Request changes**

2020-01-28 13:46 UTC, MauricioRobayo commented on style.css
> +  margin: -3px 0;
Maybe you can remove this negative margin to fix the issue with the dividers. Just an idea, not sure if that's the issue or if removing that will mess up something else.

2020-01-28 13:46 UTC, MauricioRobayo commented on index.html
> +    <p class="copyright">
This should be inside the `footer` tag.

2020-01-28 13:46 UTC, MauricioRobayo commented on index.html
> +    <div class="thumbnails-container">
OPTIONAL: You could use the `main` tag here for more semantic markup.

2020-01-28 16:44 UTC, nikasulo requested changes
# Nice work implementing the tag changes!
However, the issues I pointed out in my previous review as regards the horizontal scroll still persist, and the issues @MauricioRobayo rightly pointed out regarding the navigation are still in play. 

Please attend to the issues described in the two previous PR reviews and submit for another review!

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-02-03 17:11 UTC, nikasulo requested changes
# Really great work @Krishnabot :rocket: 
Your navigation bar is wonderfully done and looks great now! :handshake:. The horizontal scroll bug still persists and now images aren't showing up for some reason :frowning:. Please consider my comments below:

#### Horizontal Scroll
You seem to have a little bug with one of the elements of the page, shooting out beyond the browser's maximum width. This may be as a result of a margin or padding you have set up. One of the easiest ways I have found to correct this issue is to set the default `box-sizing` property to `border-box` as follows `*{box-sizing: border-box}`. Please read some more about it [here](https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing).

#### Live link
Please remember to update the live link in your project to point to the actual website. My go to resource for making live links is [Raw Githack](https://raw.githack.com) Please check it out, it's free and easy to use :+1: 

#### Images not showing up
Please consider the following screenshot. The images on the page no longer show up for some reason. Kindly look into this and apply the appropriate fix! :rocket: 
![screenshot](https://images2.imgbox.com/f3/5f/MGIbFcrI_o.png)

[OPTIONAL] Do you mind sending me a message on slack so we can discuss some of this?

Looking forward to hearing from you :smile: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-02-05 09:16 UTC, nikasulo approved these changes
# This is exquisite work! @Krishnabot :medal_military: 
It is really great how far you've come and I congratulate you. Please keep your level of hard work and tenacity up as it is cummulative and will pay of big time. You may merge this and carry on! See you at the very top :rocket: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-02-05 09:18 UTC, merged